# Generated by Django 4.2.7 on 2023-12-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_mymodel_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='department',
            new_name='department_name',
        ),
    ]
